const HTML = [
'<!DOCTYPE html>',
'<html lang="en">',
'<head>',
'<meta charset="UTF-8">',
'<meta name="viewport" content="width=device-width, initial-scale=1.0">',
'<title>WiFi CRUD</title>',
'<script src="https://cdn.tailwindcss.com"></script>',
'</head>',
'<body class="bg-gray-900 text-gray-100 min-h-screen">',
'<div id="app" class="max-w-5xl mx-auto p-6">',
'',
'<div id="login-view">',
'<div class="flex items-center justify-center min-h-screen">',
'<div class="w-full max-w-sm bg-gray-800 rounded-2xl shadow-xl p-8">',
'<h1 class="text-2xl font-bold text-center mb-2">WiFi CRUD</h1>',
'<p class="text-gray-400 text-center text-sm mb-6">IoT Tracking Dashboard</p>',
'<div id="login-error" class="bg-red-900/50 text-red-300 text-sm rounded-lg p-3 mb-4 hidden"></div>',
'<input id="login-user" type="text" placeholder="Username" class="w-full bg-gray-700 rounded-lg px-4 py-2.5 mb-3 focus:outline-none focus:ring-2 focus:ring-blue-500">',
'<input id="login-pass" type="password" placeholder="Password" class="w-full bg-gray-700 rounded-lg px-4 py-2.5 mb-4 focus:outline-none focus:ring-2 focus:ring-blue-500">',
'<button onclick="login()" class="w-full bg-blue-600 hover:bg-blue-700 font-semibold rounded-lg px-4 py-2.5 transition">Login</button>',
'</div>',
'</div>',
'</div>',
'',
'<div id="dashboard-view" class="hidden">',
'<div class="flex items-center justify-between mb-8">',
'<h1 class="text-2xl font-bold">WiFi CRUD</h1>',
'<button onclick="logout()" class="bg-gray-700 hover:bg-gray-600 text-sm rounded-lg px-4 py-2 transition">Logout</button>',
'</div>',
'',
'<div class="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6">',
'<div class="bg-gray-800 rounded-xl p-5">',
'<h2 class="text-lg font-semibold mb-3">Devices</h2>',
'<div id="device-list" class="space-y-2"></div>',
'</div>',
'<div class="bg-gray-800 rounded-xl p-5">',
'<h2 class="text-lg font-semibold mb-3">Quick Filters</h2>',
'<div class="space-y-2">',
'<input id="filter-device" type="text" placeholder="Device ID" class="w-full bg-gray-700 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500">',
'<input id="filter-bssid" type="text" placeholder="BSSID (e.g. 00:11:22:33:44:55)" class="w-full bg-gray-700 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500">',
'<div class="flex gap-2">',
'<input id="filter-start" type="number" placeholder="Start timestamp" class="flex-1 bg-gray-700 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500">',
'<input id="filter-end" type="number" placeholder="End timestamp" class="flex-1 bg-gray-700 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500">',
'</div>',
'<button onclick="loadMeasurements()" class="w-full bg-blue-600 hover:bg-blue-700 rounded-lg py-2 text-sm font-semibold transition">Apply Filters</button>',
'</div>',
'</div>',
'</div>',
'',
'<div class="bg-gray-800 rounded-xl p-5">',
'<h2 class="text-lg font-semibold mb-3">Measurements <span id="meas-count" class="text-gray-400 text-sm font-normal"></span></h2>',
'<div id="measurement-list" class="space-y-3"></div>',
'</div>',
'</div>',
'',
'</div>',
'',
'<script>',
'const API = "https://wifi-crud.lorenzo-chiroli.workers.dev";',
'let token = localStorage.getItem("token");',
'',
'function login() {',
'  const u = document.getElementById("login-user").value;',
'  const p = document.getElementById("login-pass").value;',
'  const err = document.getElementById("login-error");',
'  err.classList.add("hidden");',
'  fetch(API + "/api/users/login", {',
'    method: "POST", headers: {"Content-Type": "application/json"},',
'    body: JSON.stringify({username: u, password: p})',
'  }).then(r => r.json()).then(d => {',
'    if (d.session_token) {',
'      localStorage.setItem("token", d.session_token);',
'      token = d.session_token;',
'      document.getElementById("login-view").classList.add("hidden");',
'      document.getElementById("dashboard-view").classList.remove("hidden");',
'      loadDevices();',
'      loadMeasurements();',
'    } else {',
'      err.textContent = d.error || "Login failed";',
'      err.classList.remove("hidden");',
'    }',
'  }).catch(() => { err.textContent = "Connection error"; err.classList.remove("hidden"); });',
'}',
'',
'function logout() {',
'  localStorage.removeItem("token");',
'  token = null;',
'  document.getElementById("dashboard-view").classList.add("hidden");',
'  document.getElementById("login-view").classList.remove("hidden");',
'}',
'',
'function loadDevices() {',
'  fetch(API + "/api/devices", {headers: {"Authorization": "Bearer " + token}})',
'    .then(r => r.json()).then(list => {',
'      const el = document.getElementById("device-list");',
'      if (!list.length) { el.innerHTML = "<p class=\\"text-gray-400 text-sm\\">No devices registered.</p>"; return; }',
'      el.innerHTML = list.map(d =>',
'        "<div class=\\"bg-gray-700/50 rounded-lg p-3 flex justify-between items-center\\">" +',
'          "<div><p class=\\"font-medium\\">" + (d.name || "Unnamed") + "</p>" +',
'          "<p class=\\"text-xs text-gray-400 font-mono\\">" + d.id + "</p></div>" +',
'          "<span class=\\"text-xs text-gray-500\\">" + new Date(d.created_at * 1000).toLocaleDateString() + "</span>" +',
'        "</div>"',
'      ).join("");',
'    });',
'}',
'',
'function loadMeasurements() {',
'  const p = new URLSearchParams();',
'  const dev = document.getElementById("filter-device").value;',
'  const bssid = document.getElementById("filter-bssid").value;',
'  const st = document.getElementById("filter-start").value;',
'  const en = document.getElementById("filter-end").value;',
'  if (dev) p.set("device_id", dev);',
'  if (bssid) p.set("bssid", bssid);',
'  if (st) p.set("start_time", st);',
'  if (en) p.set("end_time", en);',
'  p.set("limit", "50");',
'  fetch(API + "/api/measurements?" + p, {headers: {"Authorization": "Bearer " + token}})',
'    .then(r => r.json()).then(d => {',
'      const el = document.getElementById("measurement-list");',
'      document.getElementById("meas-count").textContent = d.total ? "(" + d.total + " total)" : "";',
'      if (!d.measurements || !d.measurements.length) {',
'        el.innerHTML = "<p class=\\"text-gray-400 text-sm\\">No measurements found.</p>"; return;',
'      }',
'      el.innerHTML = d.measurements.map(m => {',
'        const gps = m.gps_lat != null ? m.gps_lat.toFixed(4) + ", " + m.gps_lon.toFixed(4) : "\u2014";',
'        const scans = m.wifi_scans && m.wifi_scans.length',
'          ? "<details class=\\"mt-2\\"><summary class=\\"text-xs text-blue-400 cursor-pointer hover:text-blue-300\\">WiFi Scans (" + m.wifi_scans.length + ")</summary><div class=\\"mt-2 space-y-1\\">"',
'            + m.wifi_scans.map(s =>',
'              "<div class=\\"flex justify-between text-xs bg-gray-800 rounded px-3 py-1.5\\">"',
'              + "<span>" + (s.ssid || "\u2014") + "</span>"',
'              + "<span class=\\"font-mono text-gray-400\\">" + s.bssid + "</span>"',
'              + "<span class=\\"" + (s.rssi < -75 ? "text-red-400" : "text-green-400") + "\\">" + s.rssi + " dBm</span>"',
'              + "</div>"',
'            ).join("")',
'          + "</div></details>"',
'          : "";',
'        return "<div class=\\"bg-gray-700/50 rounded-lg p-4\\">"',
'          + "<div class=\\"flex justify-between items-start mb-2\\">"',
'          + "<div><p class=\\"font-mono text-xs text-gray-400\\">" + m.device_id + "</p>"',
'          + "<p class=\\"text-sm mt-1\\">" + new Date(m.timestamp * 1000).toLocaleString() + "</p></div>"',
'          + "<div class=\\"text-right text-sm\\"><p>" + gps + "</p></div>"',
'          + "</div>"',
'          + scans',
'          + "</div>";',
'      }).join("");',
'    });',
'}',
'',
'if (token) {',
'  document.getElementById("login-view").classList.add("hidden");',
'  document.getElementById("dashboard-view").classList.remove("hidden");',
'  loadDevices();',
'  loadMeasurements();',
'}',
'</script>',
'</body>',
'</html>',
].join('\n');

export default {
  async fetch(): Promise<Response> {
    return new Response(HTML, {
      headers: { "Content-Type": "text/html; charset=utf-8" },
    });
  },
};
